[platformio]
default_envs = esp32-s3-devkitc-1
description = ESP32S3_Stepper

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = COM6
monitor_port = COM6
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps = 
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4

[env:esp32-s3-ota]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_protocol = espota
upload_port = esp32s3-stepper.local
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps = 
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4



